### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by guol-fnst** [seaweedfs/seaweedfs#3460]
```
Error: filer/filer_notify_test.go:42:16: undefined: proto.MarshalTextString
Error: filer/filer_notify_test.go:45:8: undefined: proto.UnmarshalText
```
Introduced in commit https://github.com/seaweedfs/seaweedfs/commit/eaeb141b09326aa7c4d1d1e7b7f27e119d019f9c

```
	text := proto.MarshalTextString(notification)

	notification2 := &filer_pb.EventNotification{}
	proto.UnmarshalText(text, notification2)
```
MarshalTextString should be replaced by Marshal
UnmarshalText shoule be replaced by Unmarshal
