### ISSUE TITLE
[filer] error JSON response status 500: unmarshal 

### ISSUE THREAD

**Issue by kmlebedev** [seaweedfs/seaweedfs#3812]
**Describe the bug**

error JSON response status 500: unmarshal if dns problem resolving

**System Setup**
`3.28`

**Additional context**
error log:

```
I1010 07:35:27.088891 filer_deletion.go:58 deleting fileIds len=1 error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup fast-volume-2 on 169.254.25.10:53: no such host"
I1010 07:35:26.735685 common.go:113 error JSON response status 500: unmarshal http://fast-volume-13.s3-fast-volume.service.dck12.consul:8080/109,099fa5dcce9d2750?fsync=true: invalid character '{' after top-level value
E1010 07:35:26.735666 filer_server_handlers_write_upload.go:209 upload error: unmarshal http://fast-volume-13:8080/109,099fa5dcce9d2750?fsync=true: invalid character '{' after top-level value
```

**Comment by t3hmrman** [comment]
Running into this as well, not sure what it comes from... I'm running the `warp` benchmark and it's coming up (so it's not workload specific)

**Comment by t3hmrman** [comment]
Hey @kmlebedev have you double/triple checked your networking? 

I just double checked my network stack (Calico, running on k8s w/ wireguard) and found that there were connectivity issues from volume server to volume server, in particular.

I treat my storage nodes a little differently and it turns out they weren't able to have direct access to each other (note that this is even with `readMode=redirect` on -- obviously writes won't get replicated properly), but other pieces of infra were able to reach properly.

Maybe my problem and yours are different, but it looks like replication failures between nodes were causing my issues.

**Comment by kmlebedev** [comment]
Possibly related to https://github.com/seaweedfs/seaweedfs/pull/4188

After updating this week to v3.43 I will check if the error is gone
